Repository CS3219-AY2425S1/cs3219-ay2425s1-project-g05, pull requests merged in 2024-11, with the labels that each got.

#104 chore: Update Docker Compose File
  docker-compose.yaml
Labels: stack.DevOps

#95 chore: Offload Question Query to Matching Service from Collaboration Service
  matching-service/controllers/controller.js
Labels: stack.Backend

#107 bug: Fix Collaboration Service Bug
  collaboration-service/package-lock.json
  collaboration-service/package.json
  collaboration-service/server.js
  collaboration-service/src/errors/InvalidArgumentError.js
  collaboration-service/src/errors/RoomCapacityError.js
  collaboration-service/src/server/utils.js
  collaboration-service/src/session/api.js
  collaboration-service/src/session/client.js
  collaboration-service/test/test-api.js
  collaboration-service/test/test-client.js
  peer-prep/src/pages/Session/Create/CreateSessionPage.tsx
  peer-prep/src/pages/Session/SessionPage/SessionPage.tsx
  user-service/controllers/user-controller.js
  user-service/middlewares/access-control.js
  user-service/models/repository.js
  user-service/models/user-orm.js
  user-service/package-lock.json
  user-service/package.json
  user-service/server.js
  user-service/services.js
  user-service/test/changeDisplayName.test.js
  user-service/test/changePassword.test.js
  user-service/test/constants/testTokens.js
  user-service/test/delete.test.js
  user-service/test/getUser.test.js
  user-service/test/healthz.test.js
  user-service/test/login.test.js
  user-service/test/logout.test.js
  user-service/test/mockdb.js
  user-service/test/register.test.js
Labels: chore.Bug

#108 fix: add statusCode 204
  history-service/controller/history-controller.js
  history-service/middlewares/validation.js
  question-service/controller/question-controller.js
  user-service/services.js
Labels: stack.Backend

#116 chore: Add nginx config for tracking
  nginx/nginx.conf
Labels: chore.FunctionalRequirements, f9.Nginx

#114 feat: Add matching service authentication
  matching-service/controllers/socketHandler.js
  matching-service/middlewares/access-control.js
  matching-service/package-lock.json
  matching-service/package.json
  matching-service/services.js
  peer-prep/src/pages/Session/Create/CreateSessionPage.tsx
Labels: n2.MatchingService, attribute.Security

#115 chore: Update Collaboration Service with JWT Authorization
  collaboration-service/server.js
  collaboration-service/src/middlewares/access-control.js
  collaboration-service/src/router/router.js
  peer-prep/src/components/CollabCodeEditor/CollabCodeEditor.tsx
Labels: f4.CollaborationService, attribute.Security

#112 Question service Enhancements
  peer-prep/src/main.tsx
  question-service/controller/question-controller.js
  question-service/data/questions.json
  question-service/middlewares/access-control.js
  question-service/middlewares/validation.js
  question-service/models/model.js
  question-service/models/orm.js
  question-service/models/repository.js
  question-service/router/router.js
  question-service/utils/index.js
  question-service/utils/services.js
  user-service/package-lock.json
Labels: stack.Backend, chore.Task, f3.QuestionService
