Repository CS3219-AY2425S1/cs3219-ay2425s1-project-g05, pull requests merged in 2024-10, with the labels that each got.

#54 fix: Fix Bug Reporting Template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: stack.Documentation, priority.Low, severity.Low, stack.DevOps, chore.Bug, chore.Task

#30 DevOps: Create GitHub Actions CI Files
  .github/workflows/generic.yml
  .github/workflows/production.yml
  .github/workflows/staging.yml
Labels: stack.DevOps, stack.Cloud, chore.Task

#56 Standardised API Response in Question Service with additional fields (templateCode, solutionCode and link)
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/generic.yml
  .github/workflows/production.yml
  .github/workflows/staging.yml
  question-service/controller/question-controller.js
  question-service/middlewares/errorHandler.js
  question-service/middlewares/validation.js
  question-service/models/model.js
  question-service/models/repository.js
Labels: stack.Backend, chore.Task, f3.QuestionService

#52 Fix: User service standardise API response
  user-service/controllers/user-controller.js
  user-service/server.js
Labels: priority.Low, stack.Backend, chore.Task, f1.UserService

#74 fix: Align Frontend with Standardized Backend Response Structure
  peer-prep/src/hooks/useApi.tsx
  peer-prep/src/hooks/useAuth.tsx
  peer-prep/src/pages/Questions/CreateQuestionPage/CreateQuestionPage.tsx
  peer-prep/src/pages/Questions/EditQuestionPage/EditQuestionPage.tsx
  peer-prep/src/pages/Questions/QuestionPage.tsx
  peer-prep/src/pages/Session/Create/CreateSessionPage.tsx
  peer-prep/src/types/question.ts
  peer-prep/src/types/user.ts
Labels: stack.Frontend, chore.Task

#81 feat: Implement Matching Service
  docker-compose.yaml
  matching-service/Dockerfile
  matching-service/Dockerfile.public
  matching-service/controllers/controller.js
  matching-service/controllers/socketHandler.js
  matching-service/middlewares/cors.js
  matching-service/models/orm.js
  matching-service/models/pendingUser-model.js
  matching-service/models/repository.js
  matching-service/package-lock.json
  matching-service/package.json
  matching-service/server.js
  matching-service/services.js
  matching-service/task-definition.json
Labels: priority.High, stack.Backend, chore.Feature, f2.MatchingService, chore.FunctionalRequirements

#82 feat: Implement Matching flow and update Question CRUD
  cleanup-dev.sh
  peer-prep/package-lock.json
  peer-prep/package.json
  peer-prep/src/assets/loginimage.svg
  peer-prep/src/assets/matchimage.svg
  peer-prep/src/assets/nomatchimage.svg
  peer-prep/src/components/Alert/AlertBox.module.css
  peer-prep/src/components/Alert/AlertBox.tsx
  peer-prep/src/components/AvatarIcon/AvatarWithDetailsButton.tsx
  peer-prep/src/components/Navbar/Navbar.module.css
  peer-prep/src/components/Navbar/Navbar.tsx
  peer-prep/src/components/Questions/Category/Category.tsx
  peer-prep/src/components/Questions/LanguageSelector/LanguageSelector.tsx
  peer-prep/src/components/Questions/QuestionCard/QuestionCard.module.css
  peer-prep/src/components/Questions/QuestionCard/QuestionCard.tsx
  peer-prep/src/components/Questions/RichTextEditor/RichTextEditor.tsx
  peer-prep/src/components/Statistics/StatisticCard.module.css
  peer-prep/src/components/Statistics/StatisticCard.tsx
  peer-prep/src/hooks/useAuth.tsx
  peer-prep/src/main.tsx
  peer-prep/src/pages/AdminRouteWrapper.tsx
  peer-prep/src/pages/Dashboard/DashboardPage.tsx
  peer-prep/src/pages/Home/HomePage.module.css
  peer-prep/src/pages/Home/HomePage.tsx
  peer-prep/src/pages/Login/LoginPage.tsx
  peer-prep/src/pages/ProtectedRouteWrapper.tsx
  peer-prep/src/pages/Questions/CreateQuestionPage/CreateQuestionPage.module.css
  peer-prep/src/pages/Questions/CreateQuestionPage/CreateQuestionPage.tsx
  peer-prep/src/pages/Questions/EditQuestionPage/EditQuestionPage.module.css
  peer-prep/src/pages/Questions/EditQuestionPage/EditQuestionPage.tsx
  peer-prep/src/pages/Questions/QuestionPage.tsx
  peer-prep/src/pages/Questions/QuestionsPage.module.css
  peer-prep/src/pages/Questions/QuestionsPage.tsx
  peer-prep/src/pages/Questions/ReadQuestionPage/ReadQuestionPage.module.css
  peer-prep/src/pages/Questions/ReadQuestionPage/ReadQuestionPage.tsx
  peer-prep/src/pages/Session/Create/CreateSessionPage.module.css
  peer-prep/src/pages/Session/Create/CreateSessionPage.tsx
  peer-prep/src/pages/Session/Search/SearchingPage.module.css
  peer-prep/src/pages/Session/Search/SearchingPage.tsx
  peer-prep/src/types/question.ts
  peer-prep/src/types/user.ts
  peer-prep/src/websockets/socket.ts
  start-dev.sh
Labels: f2.MatchingService, f3.QuestionService

#85 [#38] User service soft delete users
  user-service/controllers/user-controller.js
  user-service/models/repository.js
  user-service/models/user-model.js
Labels: stack.Backend, f1.UserService

#75 Question Service Categories Id
  question-service/constants/categories.js
  question-service/controller/question-controller.js
  question-service/data/questions.json
  question-service/errors/ForbiddenError.js
  question-service/errors/UnauthorisedError.js
  question-service/middlewares/access-control.js
  question-service/middlewares/validation.js
  question-service/models/model.js
  question-service/models/orm.js
  question-service/models/repository.js
  question-service/router/router.js
Labels: stack.Backend, chore.Task, f3.QuestionService
