Repository CS3219-AY2425S1/cs3219-ay2425s1-project-g05, pull requests merged in 2024-09, with the labels that each got.

#2 Update Issues Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/functional-requirement.md
  .github/ISSUE_TEMPLATE/high-level-requirement.md
  .github/ISSUE_TEMPLATE/individual-feature.md
  .github/ISSUE_TEMPLATE/non-functional-requirement.md
Labels: chore.Task

#3 Update PR Templates
  .github/pull_request_template.md
  README.md
Labels: chore.Task

#4 Create Contribution Documentation
  .github/CONTRIBUTING.md
Labels: chore.Task

#6 User Service Setup
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/functional-requirement.md
  .github/ISSUE_TEMPLATE/high-level-requirement.md
  .github/ISSUE_TEMPLATE/individual-feature.md
  .github/ISSUE_TEMPLATE/non-functional-requirement.md
  README.md
  user-service/.gitignore
  user-service/controllers/auth-controller.js
  user-service/controllers/user-controller.js
  user-service/middlewares/access-control.js
  user-service/models/repository.js
  user-service/models/user-model.js
  user-service/models/user-orm.js
  user-service/package-lock.json
  user-service/package.json
  user-service/routers/auth-router..js
  user-service/routers/user-router.js
  user-service/server.js
  user-service/services.js
Labels: stack.Backend, issue.Duplicate, chore.Task, f1.UserService, n1.UserService

#7 Merge user service staging setup files
  user-service/.gitignore
  user-service/controllers/auth-controller.js
  user-service/controllers/user-controller.js
  user-service/middlewares/access-control.js
  user-service/models/repository.js
  user-service/models/user-model.js
  user-service/models/user-orm.js
  user-service/package-lock.json
  user-service/package.json
  user-service/routers/auth-router..js
  user-service/routers/user-router.js
  user-service/server.js
  user-service/services.js
Labels: stack.Backend, f1.UserService

#11 Chore: Fix Individual Issues Templates
  .github/ISSUE_TEMPLATE/individual-feature.md
Labels: chore.Bug

#32 User Service with Login/Logout and User Management
  user-service/Dockerfile
  user-service/controllers/auth-controller.js
  user-service/controllers/user-controller.js
  user-service/middlewares/access-control.js
  user-service/middlewares/cors.js
  user-service/models/repository.js
  user-service/models/user-model.js
  user-service/models/user-orm.js
  user-service/package-lock.json
  user-service/package.json
  user-service/routers/auth-router..js
  user-service/routers/user-router.js
  user-service/server.js
  user-service/services.js
Labels: priority.High, stack.Backend, chore.Feature, f1.UserService, chore.FunctionalRequirements

#29 Question Service with CRUD and Filter Operations
  .gitignore
  question-service/Dockerfile
  question-service/controller/question-controller.js
  question-service/errors/BadRequestError.js
  question-service/errors/BaseError.js
  question-service/errors/ConflictError.js
  question-service/errors/ForbiddenError.js
  question-service/errors/NotFoundError.js
  question-service/index.js
  question-service/middlewares/access-control.js
  question-service/middlewares/cors.js
  question-service/middlewares/errorHandler.js
  question-service/middlewares/logging.js
  question-service/middlewares/validation.js
  question-service/models/model.js
  question-service/models/orm.js
  question-service/models/repository.js
  question-service/package-lock.json
  question-service/package.json
  question-service/router/router.js
Labels: stack.Backend, chore.Feature, f3.QuestionService

#5 DevOps: Create AWS Lambda Scripts for Integration
  aws/README.md
  aws/apigw/API Gateway-staging-oas30-apigateway.yaml
  aws/lambda/code_execution_statistics.py
  aws/lambda/images/runner/Dockerfile.lambda
  aws/lambda/images/runner/handler.py
  aws/lambda/jwt_authoriser.py
Labels: stack.Backend, stack.DevOps, stack.Cloud, chore.Feature, n1.UserService, n2.MatchingService, n3.QuestionService, n4.CollaborationService

#43 Frontend Integration for User Service and Question Service
  node_modules/.package-lock.json
  package-lock.json
  package.json
  peer-prep/.gitignore
  peer-prep/.vite/deps_temp_16910cd1/package.json
  peer-prep/README.md
  peer-prep/eslint.config.js
  peer-prep/index.html
  peer-prep/package-lock.json
  peer-prep/package.json
  peer-prep/postcss.config.cjs
  peer-prep/src/App.tsx
  peer-prep/src/assets/loginimage.svg
  peer-prep/src/assets/searchimage.svg
  peer-prep/src/components/ApplicationWrapper.tsx
  peer-prep/src/components/AvatarIcon/AvatarWithDetailsButton.tsx
  peer-prep/src/components/Navbar/Navbar.module.css
  peer-prep/src/components/Navbar/Navbar.tsx
  peer-prep/src/components/Questions/Category/Category.module.css
  peer-prep/src/components/Questions/Category/Category.tsx
  peer-prep/src/components/Questions/Complexity/Complexity.tsx
  peer-prep/src/components/Questions/QuestionCard/QuestionCard.module.css
  peer-prep/src/components/Questions/QuestionCard/QuestionCard.tsx
  peer-prep/src/hooks/useApi.tsx
  peer-prep/src/hooks/useAuth.tsx
  peer-prep/src/index.css
  peer-prep/src/main.tsx
  peer-prep/src/pages/AdminRouteWrapper.tsx
  peer-prep/src/pages/Dashboard/DashboardPage.module.css
  peer-prep/src/pages/Dashboard/DashboardPage.tsx
  peer-prep/src/pages/Home/HomePage.module.css
  peer-prep/src/pages/Home/HomePage.tsx
  peer-prep/src/pages/Login/LoginPage.module.css
  peer-prep/src/pages/Login/LoginPage.tsx
  peer-prep/src/pages/ProtectedRouteWrapper.tsx
  peer-prep/src/pages/Questions/CreateQuestionPage/CreateQuestionPage.module.css
  peer-prep/src/pages/Questions/CreateQuestionPage/CreateQuestionPage.tsx
  peer-prep/src/pages/Questions/EditQuestionPage/EditQuestionPage.module.css
  peer-prep/src/pages/Questions/EditQuestionPage/EditQuestionPage.tsx
  peer-prep/src/pages/Questions/QuestionPage.module.css
  peer-prep/src/pages/Questions/QuestionPage.tsx
  peer-prep/src/pages/Session/Create/CreateSessionPage.module.css
  peer-prep/src/pages/Session/Create/CreateSessionPage.tsx
  peer-prep/src/pages/Session/Search/SearchingPage.module.css
  peer-prep/src/pages/Session/Search/SearchingPage.tsx
  peer-prep/src/types/question.ts
  peer-prep/src/types/user.ts
  peer-prep/src/utils/utils.ts
  peer-prep/src/vite-env.d.ts
  peer-prep/tsconfig.app.json
  peer-prep/tsconfig.json
  peer-prep/tsconfig.node.json
  peer-prep/vite.config.ts
Labels: stack.Frontend, chore.Feature, f1.UserService, f3.QuestionService

#47 Fix: Minor bug for Create Question page difficulty dropdown
  peer-prep/src/pages/Questions/CreateQuestionPage/CreateQuestionPage.tsx
Labels: stack.Frontend, chore.Bug, n3.QuestionService
